
const PRODUCTOS = [
    {
        id: 1,
        precio: 1389,
        marca: "HEINEKEN",
        img: "../resources/prod_01.png",
        bebidaConAlcohol: true,
        consumoPromedio: 1,
        litrosBotella: 0.330,
        nombre: "Cerveza Rubia",
    },
    {
        id: 2,
        precio: 1215,
        marca: "MILLER",
        img: "../resources/prod_02.png",
        bebidaConAlcohol: true,
        consumoPromedio: 1,
        litrosBotella: 0.330,
        nombre: "Cerveza Rubia",
    },
    {
        id: 3,
        precio: 3682,
        marca: "CORDERO CON PIEL DE LOBO",
        img: "../resources/prod_03.png",
        bebidaConAlcohol: true,
        consumoPromedio: 0.5,
        litrosBotella: 0.75,
        nombre: "Vino malbec",
    },
    {
        id: 4,
        precio: 3240,
        marca: "PORTILLO",
        img: "../resources/prod_04.png",
        bebidaConAlcohol: true,
        consumoPromedio: 0.5,
        litrosBotella: 0.75,
        nombre: "Vino malbec",
    },
    {
        id: 5,
        precio: 1400,
        marca: "VILLA DEL SUR",
        img: "../resources/prod_05.png",
        bebidaConAlcohol: false,
        consumoPromedio: 0.750,
        litrosBotella: 2.25,
        nombre: "Agua mineral sin gas",
    },
    {
        id: 6,
        precio: 1050,
        marca: "SALDAN",
        img: "../resources/prod_06.png",
        bebidaConAlcohol: false,
        consumoPromedio: 0.750,
        litrosBotella: 2,
        nombre: "Soda sifón",
    },
    {
        id: 7,
        precio: 3050,
        marca: "SPRITE",
        img: "../resources/prod_07.png",
        bebidaConAlcohol: false,
        consumoPromedio: 0.750,
        litrosBotella: 2.25,
        nombre: "Gaseosa lima limón",
    },
    {
        id: 8,
        precio: 3250,
        marca: "COCA-COLA",
        img: "../resources/prod_08.png",
        bebidaConAlcohol: false,
        consumoPromedio: 0.750,
        litrosBotella: 2.50,
        nombre: "Gaseosa sabor original",
    },
];